title: "[공지사항]  "
body:
- type: dropdown
  attributes:
    label: 카테고리
    multiple: false
    options:
      - 전체 공지
      - 통신 관련
      - 코드 관련
      - 기타
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: 전달 사항
    value: |
      * text
      * text
      * text
