title: " 제목작성 "
body:
- type: textarea
  attributes:
    label: 공유 정보
    value: |
      * text
      * text
      * text
- type: textarea
  attributes:
    label: 첨부 코드
    value: |
      ```javascript
      code
      ```
